### ISSUE TITLE
NoMethodError: undefined method `stream' for #<Redd::Models::Listing:0x00007fe99deb75b0>

### ISSUE THREAD

**Issue by StephanMeijer** [avinashbot/redd#81]

**Comment by JakeTompkins** [comment]
Getting the same error.

**Comment by StephanMeijer** [comment]
```
[1] pry(main)> Rails.configuration.redd.subreddit('all')
=> #<Redd::Models::Subreddit:0x00007fbe2492ca90 ...>
  display_name: all
[2] pry(main)> Rails.configuration.redd.subreddit('all').comments.stream
NoMethodError: undefined method `stream' for #<Redd::Models::Listing:0x00007fbe239dc838>
from /Users/steve/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/redd-0.8.8/lib/redd/models/basic_model.rb:57:in `method_missing'
[3] pry(main)> Rails.configuration.redd
=> #<Redd::Models::Session:0x00007fbe25f30d50 ...>

[4] pry(main)> Rails.configuration.redd.subreddit('all').comments
=> #<Redd::Models::Listing:0x00007fbe25d31900 ...>
  modhash:
  dist: 25
  children: [#<Redd::Models::Comment:0x00...
```

```
[2] pry(main)> Rails.configuration.redd.subreddit('all').comments.stream

NoMethodError: undefined method `stream' for #<Redd::Models::Listing:0x00007fbe239dc838>
from /Users/steve/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/redd-0.8.8/lib/redd/models/basic_model.rb:57:in `method_missing'
```

**Comment by StephanMeijer** [comment]
Solved by `gem 'redd', github: 'avinashbot/redd'` or `gem specific_install -l https://github.com/avinashbot/redd.git`
